export default {
    LOGIN_REQUEST: '@@login/LOGIN_REQUEST',
    LOGIN_SUCCESS: '@@login/LOGIN_SUCCESS',
    LOGIN_ERROR: '@@login/LOGIN_ERROR',
    LOGOUT_REQUEST: '@@login/LOGOUT_REQUEST',
    AUTO_LOGIN_ERROR: '@@login/AUTO_LOGIN_ERROR',
};